const alphabetArray = [
    { name: "a", isUsed: false},
    { name: "b", isUsed: false},
    { name: "c", isUsed: false},
    { name: "d", isUsed: false},
    { name: "e", isUsed: false},
    { name: "f", isUsed: false},
    { name: "g", isUsed: false},
    { name: "h", isUsed: false},
    { name: "i", isUsed: false},
    { name: "j", isUsed: false},
    { name: "k", isUsed: false},
    { name: "l", isUsed: false},
    { name: "m", isUsed: false},
    { name: "n", isUsed: false},
    { name: "o", isUsed: false},
    { name: "p", isUsed: false},
    { name: "q", isUsed: false},
    { name: "r", isUsed: false},
    { name: "s", isUsed: false},
    { name: "t", isUsed: false},
    { name: "u", isUsed: false},
    { name: "v", isUsed: false},
    { name: "w", isUsed: false},
    { name: "x", isUsed: false},
    { name: "y", isUsed: false},
    { name: "z", isUsed: false},
];

export default alphabetArray;
